servlet:
  context-path: /seckill
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
    initialSize: 100
    # 空闲数
    minIdle: 100
    maxActive: 500
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  rabbitmq:
    host: 106.13.128.45
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 消费者数量
        concurrency: 10
        max-concurrency: 10
        # 每次取几个
        prefetch: 1
        # 指示容器是否随着ApplicationContext的启动而启动。设置这个值为false，如果在你启动的时候消息代理还没有启动，当消息代理准备好的时候调用start()方法手动启动。
        auto-startup: true
        # 消费失败重新压入
        default-requeue-rejected: false
        retry:
          enabled: false
          max-attempts: 1
          # 重试间隔时间（单位毫秒）
          initial-interval: 1000
          # Maximum duration between attempts
          max-interval: 10000
  redis:
    host: 106.13.128.45
    port: 6379
    timeout: 10
    password: 135790
    # 太小会导致获取不到连接
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500

mybatis:
  type-aliases-package: com.seen.seckillbackend.domain.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/seen/seckillbackedn/dao/*.xml

server:
  port: 8765



redis-cluster:
  hosts: 106.13.128.45:6379
  timeout: 10
  password: 135790
  # 太小会导致获取不到连接
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500